version: '3'
services:
  emrapp-postgres-db:
    image: postgres
    container_name: emrapp-postgres-db
    environment:
      POSTGRES_DB: emrapp-db-postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${PWD}/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - emrapp-postgres-db