version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres1
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
