name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
#    env:
#      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Build
        run: mvn clean package -q

      - name: Get  Version from pom.xml
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "$VERSION"
          ls 
          ls target
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-ehr-${{ env.VERSION }}
          path: target/emrapp*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: VERSION=${{ env.VERSION }}
          tags: sammyhtb/prime-ehr:${{ env.VERSION }}

