---
name: Java CI with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: postgres
          password: postgres1
          database: emrapp
          port: 5432
        id: postgres
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      - name: Before
        run: ls -la
        
      - name: Maven version
        run: mvn package
        
      - name: After
        run: ls -la
