name: Docker Compose Actions

on:
  push:
    branches:
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Docker Compose Up
        run: |
          docker-compose up -d

      - name: Docker Compose Down
        run: |
          docker-compose down