name: Docker Compose Actions

on:
  pull_request:
    branches:
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Docker Compose Up
        run: |
          docker-compose up -d

      - name: Run Spring Boot application
        run: java -jar target/*.jar

      - name: Docker Compose Down
        run: |
          docker-compose down